Repository IgniteUI/COVID-19-Dashboard, pull requests merged in 2020-03, with the labels that each got.

#32 implement data caching, clear unused files, enrich tooltips
  docs/assets/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv
  docs/assets/csse_covid_19_time_series/time_series_19-covid-Deaths.csv
  docs/assets/csse_covid_19_time_series/time_series_19-covid-Recovered.csv
  docs/index.html
  docs/main-es2015.85e1ca56881d81970f00.js
  docs/main-es5.85e1ca56881d81970f00.js
  docs/main.2faf2790d963b3763ba7.js
  docs/polyfills-es2015.9b8ecabd8e76f89df95f.js
  docs/polyfills-es5.686fc07ed80f0522c7b2.js
  docs/polyfills-es5.dcdadadeb65a8e3cfbee.js
  docs/polyfills.9e9131e3d5000414937f.js
  docs/runtime-es5.0811dcefd377500b5b1a.js
  docs/runtime.689ba4fd6cadb82c1ac2.js
  src/app/app.component.html
  src/app/app.component.ts
  src/app/footer/footer.component.html
  src/app/footer/footer.component.ts
  src/app/list-cases/list-cases.component.html
  src/app/list-cases/list-cases.component.ts
  src/app/main/main.component.ts
  src/app/map-cases/EsriMapsUtility.ts
  src/app/map-cases/map-cases.component.html
  src/app/map-cases/map-cases.component.scss
  src/app/map-cases/map-cases.component.ts
  src/app/services/data.service.ts
  src/assets/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv
  src/assets/csse_covid_19_time_series/time_series_19-covid-Deaths.csv
  src/assets/csse_covid_19_time_series/time_series_19-covid-Recovered.csv
  tsconfig.json
Labels: status: verified

#45 Fall back to localfiles
  docs/assets/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv
  docs/assets/csse_covid_19_time_series/time_series_19-covid-Deaths.csv
  docs/assets/csse_covid_19_time_series/time_series_19-covid-Recovered.csv
  docs/assets/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
  docs/assets/csse_covid_19_time_series/time_series_covid19_deaths_global.csv
  docs/assets/csse_covid_19_time_series/time_series_covid19_recovered_global.csv
  docs/index.html
  docs/main.2faf2790d963b3763ba7.js
  docs/main.3fd6abd9dfc9856f1643.js
  docs/polyfills-es5.7f34ea60dafbf18726bd.js
  src/app/main/main.component.ts
  src/app/services/data.service.ts
  src/assets/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv
  src/assets/csse_covid_19_time_series/time_series_19-covid-Deaths.csv
  src/assets/csse_covid_19_time_series/time_series_19-covid-Recovered.csv
  src/assets/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
  src/assets/csse_covid_19_time_series/time_series_covid19_deaths_global.csv
  src/assets/csse_covid_19_time_series/time_series_covid19_recovered_global.csv
Labels: status: verified

#47 Fix for splash screen and tooltips colors
  docs/index.html
  docs/main.f7deb8d0599963ee89bb.js
  package.json
  src/app/main/weather-data.ts
  src/app/map-cases/map-cases.component.html
  src/app/map-cases/map-cases.component.scss
  src/app/splashscreen/splashscreen.component.html
  src/app/splashscreen/splashscreen.component.scss
Labels: status: in-test

#48 Custom chart tooltips, bottom navigation component other visual enhancements
  angular.json
  docs/favicon.ico
  docs/index.html
  docs/main.3fd6abd9dfc9856f1643.js
  docs/main.a3cc827fe5f07bec7815.js
  docs/main.f7deb8d0599963ee89bb.js
  docs/polyfills-es5.686fc07ed80f0522c7b2.js
  docs/styles.5b6f56f5858083571fb0.css
  docs/styles.d2aafb88a102f1d2329f.css
  src/app/main/main.component.html
  src/app/main/main.component.scss
  src/app/map-cases/map-cases.component.html
  src/app/map-cases/map-cases.component.scss
  src/app/themes/components/_dark.scss
  src/app/themes/components/_light.scss
  src/app/themes/components/bottom-nav/_dark.scss
  src/app/themes/components/bottom-nav/_light.scss
  src/app/themes/components/tabs/_dark.scss
  src/app/themes/components/tabs/_light.scss
  src/app/timeline-chart/timeline-chart.component.html
  src/app/timeline-chart/timeline-chart.component.scss
  src/app/timeline-chart/timeline-chart.component.ts
  src/index.html
Labels: status: resolved
